import { Data } from "./Interface";

export const emptyData: Data = {
  Id: {
    _object: false,
    _type: "xsd:string",
    _value: "",
    _timestamp: Date.now().toString(),
    _writable: false,
  },
  CurrentBitRate: {
    _type: "xsd:unsignedInt",
    _value: 0,
    _object: false,
    _timestamp: Date.now().toString(),
    _writable: false,
  },
  Enable: {
    _type: "xsd:boolean",
    _value: false,
    _object: false,
    _timestamp: Date.now().toString(),
    _writable: true,
  },
  LowerLayers: {
    _type: "xsd:string",
    _value: "",
    _object: false,
    _timestamp: Date.now().toString(),
    _writable: true,
  },
  MACAddress: {
    _type: "xsd:string",
    _value: "",
    _object: false,
    _timestamp: Date.now().toString(),
    _writable: false,
  },
  Stats: {
    BytesReceived: {
      _type: "xsd:unsignedInt",
      _value: 0,
      _object: false,
      _timestamp: Date.now().toString(),
      _writable: false,
    },
    BytesSent: {
      _type: "xsd:unsignedInt",
      _value: 0,
      _object: false,
      _timestamp: Date.now().toString(),
      _writable: false,
    },
    DiscardPacketsReceived: {
      _type: "xsd:unsignedInt",
      _value: 0,
      _object: false,
      _timestamp: Date.now().toString(),
      _writable: false,
    },
    DiscardPacketsSent: {
      _type: "xsd:unsignedInt",
      _value: 0,
      _object: false,
      _timestamp: Date.now().toString(),
      _writable: false,
    },
    ErrorsReceived: {
      _type: "xsd:unsignedInt",
      _value: 0,
      _object: false,
      _timestamp: Date.now().toString(),
      _writable: false,
    },
    ErrorsSent: {
      _type: "xsd:unsignedInt",
      _value: 0,
      _object: false,
      _timestamp: Date.now().toString(),
      _writable: false,
    },
    PacketsReceived: {
      _type: "xsd:unsignedInt",
      _value: 0,
      _object: false,
      _timestamp: Date.now().toString(),
      _writable: false,
    },
    PacketsSent: {
      _type: "xsd:unsignedInt",
      _value: 0,
      _object: false,
      _timestamp: Date.now().toString(),
      _writable: false,
    },
    _object: true,
    _timestamp: Date.now().toString(),
    _writable: false,
  },
  Status: {
    _type: "xsd:string",
    _value: "",
    _object: false,
    _timestamp: Date.now().toString(),
    _writable: false,
  },
  X_MIKROTIK_Comment: {
    _type: "xsd:string",
    _value: "",
    _object: false,
    _timestamp: Date.now().toString(),
    _writable: true,
  },
  X_MIKROTIK_LinkDowns: {
    _type: "xsd:unsignedInt",
    _value: 0,
    _object: false,
    _timestamp: Date.now().toString(),
    _writable: false,
  },
  X_MIKROTIK_Name: {
    _type: "xsd:string",
    _value: "",
    _object: false,
    _timestamp: Date.now().toString(),
    _writable: true,
  },
  _object: false,
  _timestamp: Date.now().toString(),
  _writable: false,
};
