import { Data } from "./ssid";

export const emptyData: Data = {
  Id: {
    _type: "xsd:string",
    _value: "",
    _object: false,
    _timestamp: Date.now().toString(),
    _writable: false,
  },
  BSSID: {
    _type: "xsd:string",
    _value: "",
    _object: false,
    _timestamp: Date.now().toString(),
    _writable: false,
  },
  MACAddress: {
    _type: "xsd:string",
    _value: "",
    _object: false,
    _timestamp: Date.now().toString(),
    _writable: false,
  },
  Stats: {
    BytesReceived: {
      _type: "xsd:unsignedInt",
      _value: 0,
      _object: false,
      _timestamp: Date.now().toString(),
      _writable: false,
    },
    BytesSent: {
      _type: "xsd:unsignedInt",
      _value: 0,
      _object: false,
      _timestamp: Date.now().toString(),
      _writable: false,
    },
    DiscardPacketsReceived: {
      _type: "xsd:unsignedInt",
      _value: 0,
      _object: false,
      _timestamp: Date.now().toString(),
      _writable: false,
    },
    DiscardPacketsSent: {
      _type: "xsd:unsignedInt",
      _value: 0,
      _object: false,
      _timestamp: Date.now().toString(),
      _writable: false,
    },
    ErrorsReceived: {
      _type: "xsd:unsignedInt",
      _value: 0,
      _object: false,
      _timestamp: Date.now().toString(),
      _writable: false,
    },
    ErrorsSent: {
      _type: "xsd:unsignedInt",
      _value: 0,
      _object: false,
      _timestamp: Date.now().toString(),
      _writable: false,
    },
    PacketsReceived: {
      _type: "xsd:unsignedInt",
      _value: 0,
      _object: false,
      _timestamp: Date.now().toString(),
      _writable: false,
    },
    PacketsSent: {
      _type: "xsd:unsignedInt",
      _value: 0,
      _object: false,
      _timestamp: Date.now().toString(),
      _writable: false,
    },
    _object: true,
    _timestamp: Date.now().toString(),
    _writable: false,
  },
  Enable: {
    _type: "xsd:boolean",
    _value: true,
    _object: false,
    _timestamp: Date.now().toString(),
    _writable: true,
  },
  LowerLayers: {
    _type: "xsd:string",
    _value: "",
    _object: false,
    _timestamp: Date.now().toString(),
    _writable: true,
  },
  SSID: {
    _type: "xsd:string",
    _value: "",
    _object: false,
    _timestamp: Date.now().toString(),
    _writable: true,
  },
  Status: {
    _type: "xsd:string",
    _value: "",
    _object: false,
    _timestamp: Date.now().toString(),
    _writable: false,
  },
  _object: true,
  _timestamp: Date.now().toString(),
  _writable: false,
};
